### ISSUE TITLE
how to build it

### ISSUE THREAD

**Issue by ixlm** [google/nearby#125]
it's a great work! I really like it. but i don't know how to build it, anybody knows?

**Comment by bourdakos1** [comment]
Are you trying to build connections, fast pair, embedded or presence? And for which platform?

**Comment by asteroidalaz** [comment]
Could it be used on mac (13.x+)? Any plans for making it for mac?

**Comment by bourdakos1** [comment]
Yes, this is works with macOS 13.x+ and is available through swift package manager
