### ISSUE TITLE
How to get Provider's Public Key?

### ISSUE THREAD

**Issue by kavanmevada** [google/nearby#1577]
In Fast Pair Procedure
When handling a write request from a Fast Pair Seeker, Seeker first enables Notifications on the Key-based Pairing characteristic, and then writes the data in [Table 1.1](https://developers.google.com/nearby/fast-pair/specifications/characteristics#table1.1)  to it.

It's confusing to create uint128 Encrypted Request without knowing Public Key of Provider.

In order to create shared_secret it requires Bob's(Seeker's) Private Key and Alice's(Provider's) Public Key.

Can I know how to get Provider's Public Key?

**Comment by bourdakos1** [comment]
@chunzhang999 could you take a look at this?

**Comment by kavanmevada** [comment]
Maybe you miss understood the question. I'm not talking about fastpair provider's anti spoofing keys.

How public key exchange happens between provider and seeker?

**Comment by chunzhang999** [comment]
Here is the process:
https://developers.google.com/nearby/fast-pair/specifications/service/gatt.
We use the Diffe-Hellman algorithm.
