### ISSUE TITLE
Unable to discover and advertise in iOS

### ISSUE THREAD

**Issue by fazil6669** [google/nearby#1591]
### Project

Nearby Connections

### Language

Swift

### OS Platform

Apple

### What happened?

While I try to advertise its throwing error with error message **Error Domain=kNWErrorDomainDNS Code=-65555 "DNS Error: NoAuth" UserInfo={NSDescription=DNS Error: NoAuth}** 

when I try to discover its throwing a error message as **`Failed StartDiscovery() for client=2228946243778077910 because we couldn't scan on Bluetooth, BLE, or WifiLan for serviceId`**

### What did you expect to happen?

Advertise and Discover should work as expected

### How can we reproduce it (as minimally and precisely as possible)?

1. Start discoverer 
2. Start advertiser 

### How often does this bug happen?

Every time

### Standalone code to reproduce the issue

1. Start discoverer 
2. Start advertiser 

### Relevant log output

```shell
iOS Example[15260:8251441] [browser] nw_browser_fail_on_dns_error_locked [B1] DNSServiceBrowse failed: NoAuth(-65555)

StartDiscovery() Error starting discovery for service type<_307BEAB11028._tcp.>: Error Domain=kNWErrorDomainDNS Code=-65555 "DNS Error: NoAuth" UserInfo={NSDescription=DNS Error: NoAuth}

Example[15260/0x16f39b000] [lvl=3] p2p_cluster_pcp_handler.cc:1010() Failed StartDiscovery() for client=2228946243778077910 because we couldn't scan on Bluetooth, BLE, or WifiLan for service_id=com.google.location.nearby.apps.helloconnections
```

**Comment by bourdakos1** [comment]
I've updated our sample app to include the usage descriptions and Bonjour services keys: #1592

I've also updated our documentation with more info: https://developers.google.com/nearby/connections/swift/get-started

Feel free to re-open this issue if this doesn't resolve the errors you are seeing :)

**Comment by fazil6669** [comment]
Thank you for fixing the issue so quickly! Your efficient work is greatly appreciated.
