### ISSUE TITLE
Video stream on both Android and iOS

### ISSUE THREAD

**Issue by eliabruni** [google/nearby#1670]
Hi,

This looks a great, very much needed project!

My question: I would like to set up a realtime webRTC video stream from an IoT device (running Linux) to both Android and iOS (iPhones mostly). 
The setup would look like the following: the IoT device creates a wifi hotspot; the phone needs to connect to it but without dropping its internet data as the IoT device won't have any internet; the streams from IoT to phone starts.

First I was considering wifi-direct, however, iOS doesn't support it. Would I be able to use Nearby instead?

Thanks!

**Comment by bourdakos1** [comment]
Hi @eliabruni! We don’t support any connection mediums for Linux, see #408. However, video streaming between iOS and Android would be possible using Nearby Connections.

**Comment by eliabruni** [comment]
Hi @bourdakos1, clear thanks! Any plans to support Linux in the future?

**Comment by bourdakos1** [comment]
Our current focus is Windows and Apple platforms, but we are open to external contributions

**Comment by eliabruni** [comment]
Alright, in case we decide to develop a solution we will be very happy to contribute.
