### ISSUE TITLE
Clarification on iOS/Android compatibility and future

### ISSUE THREAD

**Issue by lschmierer** [google/nearby#1720]
Hello, first of all thanks for your great work!
I am right now really confused on the state and direction of the Google Nearby products.
The Nearby Messages API (which communicates via the cloud) works for Android and iOS but will be discontinued.
For the Nearby Connections API on the other hand, the documentation states at various places that it only supports Android.
However, looking at the examples at this repository, communication between Android and iOS seems possible.
I understand that the iOS implementation is still work-in-progress.
But, is the general idea that the new Nearby Connections API will replace the use cases of the former Nearby Messages API?
And the documentation of the Nearby Connections API will be updated to reflect iOS support once ready?

I am also wondering how this all relates to the cross-device-sdk https://github.com/google/cross-device-sdk which has seen barely any development since its announcement on Google I/O 22 and has som similar objectives.

It would be nice if you could provide some information, although I understand that you probably can not make any statements about Goolgle policies and/or product decisions.

**Comment by bourdakos1** [comment]
Hey @lschmierer

Sorry for the confusion! Part of the reason we are deprecating Nearby Messages is to reduce some of the confusion between all of our offerings. This project should be able to cover most of the use cases of Nearby Messages.

Nearby Connections operates on top of “mediums”. These mediums are used to discover other devices and transfer data. Each medium has its own advantages and limitations. Android has the largest list of supported mediums while iOS currently only has 1 supported medium (Wi-Fi LAN). Wi-Fi LAN’s limitation is that both devices need to be connected to the same Wi-Fi network to function.

We are working on adding support for the BLE medium which would provide similar functionality as Nearby Messages for discovery and plan to have this ready before Nearby Messages is shut down (December 31st).

 Do you mind sharing documentation links that mention iOS not being supported so we can get those updated with more up-to-date information?

As for the cross-device-sdk, it is intended to be easier to use than Nearby Connections, but has more restrictions (also, the cross-device-sdk does not have any iOS support yet)

Hope this helps :)

**Comment by lschmierer** [comment]
Thanks for the quick response!

Right on the landing page https://developers.google.com/nearby it says "The Nearby Connections API is available for Android" while "The Nearby Messages API is available for Android and iOS". This gives me the impression that Connections API is not available for iOS.

On this site https://developers.google.com/nearby/overview it says explicitly at the bottom to use the Messages API if "you want to communicate between Android and iOS devices".
Also on the left there is only "Android" in the menu (iOS only for Messages API).

I have only just realized that there is in fact Swift documentation once one is on the Connections documentation itself (https://developers.google.com/nearby/connections/overview)

**Comment by bourdakos1** [comment]
Thanks! I’ll get those links updated :)

**Comment by lschmierer** [comment]
Just out or curiosity… I understand that there are fundamental limitations that make it impossible to establish P2P connections between Android and iOS without being connected to the same Wi-Fi AP. But would it in theory be possible to implement that direct communication for between two iOS devices? 
(Or alternatively is it be possible to use iOS Multipeer Connectivity together with the Google Nearby Connections API or would they somehow interfere?)

**Comment by bourdakos1** [comment]
Yes, we are actually experimenting with using the multipeer connectivity framework as a medium that would only be available between Apple devices, but it’s much lower priority than BLE at the moment

**Comment by RafaelKr** [comment]
In the Apple world there is the feature of "sharing a WiFi password".

If a user uses two Apple devices with the same iCloud account, e.g. iPhone and MacBook, the user can connect to a WiFi network for the first time and if the other device is nearby and already has the password stored it can share that password to the device connecting for the first time.

Is this a feature which will also be provided by the Nearby API? I read a lot in the docs but couldn't find a clear indication of such a feature. I'm using Linux & Android and would love to see that feature!

**Comment by szuniverse** [comment]
https://stackoverflow.com/questions/77612062/google-nearby-connections-api-ios-android
waiting for answers here as well

**Comment by bglgwyng** [comment]
> Yes, we are actually experimenting with using the multipeer connectivity framework as a medium that would only be available between Apple devices, but it’s much lower priority than BLE at the moment

Does this mean that we'll be able to transfer files between Android and iOS at WiFi speed(or close to it) using the multipeer connectivity framework, even when they are not in the same WiFi LAN?

**Comment by live-alchemy** [comment]
> Discovering / connecting / sharing data between iOS and Android is very possible and should work out of box as long as service IDs and strategy match and both devices are connected to the same Wi-Fi network. iOS doesn't support the full range of mediums that Android supports, so you may not be able to discover in certain scenarios.

Want to make sure I've understood this clearly, @bourdakos1 comments that Nearby Connections between iOS and Android are impossible offline, but the documentation for Nearby Connections open with:

> Nearby Connections enables advertising, discovery, and connections between nearby devices in a fully-offline peer-to-peer manner.

My company is looking at building a solution that would allow a string to be sent from one react-native application to another at a point of sale and Nearby Connections appears to be the only way forward for something cross platform, but we cannot rely on devices being on the same network. Any comments or thoughts appreciated.

**Comment by bourdakos1** [comment]
We are working on BLE support for iOS (#1619), which should allow for quickly sharing small strings while offline.

**Comment by TVGSOFT** [comment]
Hi,

During implement Nearby Connection for Android and iOS. We have a situation in 2 different Wifi LAN:
Wifi LAN 1:
 - iOS to iOS: working well
 - Android to Android: working well
 - iOS to Android: doesn't work. It can not discover each others.
 
 Wifi LAN 2: Both Android and iOS are working well.

Do you guys know any limitation of the network or restrict by it?

Thanks!

**Comment by szuniverse** [comment]
> Hi,
> 
> During implement Nearby Connection for Android and iOS. We have a situation in 2 different Wifi LAN: Wifi LAN 1:
> 
> * iOS to iOS: working well
> * Android to Android: working well
> * iOS to Android: doesn't work. It can not discover each others.
> 
> Wifi LAN 2: Both Android and iOS are working well.
> 
> Do you guys know any limitation of the network or restrict by it?
> 
> Thanks!

Hi. Based on our experience: iOS <> Android can only communicate with each other if they are on the same WiFi and if mDNS is enabled on the network. For now, it seems to us that this library works fine between the same platform, but in all other cases there are hard constraints that are hard to meet in a real scenario.

**Comment by OwenHoffend** [comment]
Has anyone had success with Android <--> IOS connectivity via BLE? For example, by enabling BLE on IOS via the method suggested in [#1619](https://github.com/google/nearby/issues/1619)?

**Comment by bourdakos1** [comment]
> Hi,
> 
> During implement Nearby Connection for Android and iOS. We have a situation in 2 different Wifi LAN: Wifi LAN 1:
> 
> * iOS to iOS: working well
> * Android to Android: working well
> * iOS to Android: doesn't work. It can not discover each others.
> 
> Wifi LAN 2: Both Android and iOS are working well.
> 
> Do you guys know any limitation of the network or restrict by it?
> 
> Thanks!

I’m not aware of any network conditions that would cause iOS <> Android to fail, but continue to work iOS <> iOS. Could you provide some logs from both the iOS and Android side?

**Comment by TVGSOFT** [comment]
@bourdakos1 Actually Android and iOS can not discover each other in some WIFI LAN network.
But in the same platform then it is OK. I'm not sure under the hood what is the root cause.

**Comment by ColtonIdle** [comment]
@bourdakos1 you asked where there was outdated info. This video from 2022 says that nearby connections api is android only. I think I also saw a mention of android only in one of the docs as well. ill try to find it. im building a nearby dice rolling game so im still new to this stuff. hope to have ios <> android working! wonder if nearby can work with apples multipeer api too

![CleanShot 2024-02-01 at 20 39 20@2x](https://github.com/google/nearby/assets/31751141/97ec2dc7-da13-48f0-904c-4a7ad11e0fa6)

**Comment by ColtonIdle** [comment]
This too
![CleanShot 2024-02-01 at 20 48 06@2x](https://github.com/google/nearby/assets/31751141/bfec4e36-7fee-452c-aacf-e9091b51191c)

**Comment by ColtonIdle** [comment]
@bglgwyng 


> Yes, we are actually experimenting with using the multipeer connectivity framework as a medium that would only be available between Apple devices, but it’s much lower priority than BLE at the moment

>> Does this mean that we'll be able to transfer files between Android and iOS at WiFi speed(or close to it) using the multipeer connectivity framework, even when they are not in the same WiFi LAN?

nope. multipeer is ios only. so what he was saying was that multipeer would work as a medium only between apple devices

**Comment by ColtonIdle** [comment]
@live-alchemy 

> Nearby Connections enables advertising, discovery, and connections between nearby devices in a fully-offline peer-to-peer manner.

I suppose being on the same LAN != being online. So I guess that statement is true since I can have a local network that's not connected to the internet and ios and android would still work. But I agree the wording is confusing. maybe @bourdakos1 can update that text a bit. 😂

**Comment by ColtonIdle** [comment]
@TVGSOFT 

> Actually Android and iOS can not discover each other in some WIFI LAN network.
But in the same platform then it is OK. I'm not sure under the hood what is the root cause.

Do you have logs from those failing devices + network you could share? Maybe it'd help identify the issue

**Comment by ColtonIdle** [comment]
Anyone able to get the ios sample working?

I get this error on iphone 15, ios 17.0.3

```
2024-02-02 10:22:17.258 iOS Example[1804/0x1e50cb880] [lvl=2] service_controller_router.cc:87() ServiceControllerRouter going up.
2024-02-02 10:22:17.260 iOS Example[1804/0x1e50cb880] [lvl=2] client_proxy.cc:65() ClientProxy ctor event_logger=0x0
2024-02-02 10:22:17.260 iOS Example[1804/0x1e50cb880] [lvl=2] analytics_recorder.cc:101() Start AnalyticsRecorder ctor event_logger_=0x0
2024-02-02 10:22:17.261 iOS Example[1804/0x1e50cb880] [lvl=2] client_proxy.cc:82() [safe-to-disconnect]: Local enabled: 0; Version: 0
2024-02-02 10:22:17.267 iOS Example[1804/0x16d05f000] [lvl=2] endpoint_manager.cc:450() EndpointManager received request to add registration of frame processor 0x10781a4d8 for frame type PAYLOAD_TRANSFER, self=0x10781a460
2024-02-02 10:22:17.268 iOS Example[1804/0x16d05f000] [lvl=2] endpoint_manager.cc:450() EndpointManager received request to add registration of frame processor 0x10781a5f8 for frame type BANDWIDTH_UPGRADE_NEGOTIATION, self=0x10781a460
2024-02-02 10:22:17.268 iOS Example[1804/0x16d05f000] [lvl=2] offline_service_controller.cc:61() Client -1399954041333141350 requested discovery to start.
2024-02-02 10:22:17.269 iOS Example[1804/0x16d05f000] [lvl=2] base_pcp_handler.cc:385() StartDiscovery with supported mediums:{ WIFI_LAN }
2024-02-02 10:22:17.269 iOS Example[1804/0x16d05f000] [lvl=2] base_pcp_handler.cc:459() Waiting for future to complete: StartDiscovery(com.rollertoaster.app)
2024-02-02 10:22:18.028 iOS Example[1804/0x16cebb000] [lvl=3] StartDiscovery() Error starting discovery for service type<_DCDE573C7B1A._tcp.>: Error Domain=kNWErrorDomainDNS Code=-65555 "DNS Error: NoAuth" UserInfo={NSDescription=DNS Error: NoAuth}
2024-02-02 10:22:18.028 iOS Example[1804/0x16cebb000] [lvl=2] wifi_lan.cc:138() WifiLan Discovery started for service_type=_DCDE573C7B1A._tcp., impl=0x280a1caf0, success=0
2024-02-02 10:22:18.028 iOS Example[1804/0x16cebb000] [lvl=2] wifi_lan.cc:167() Failed to start discovery of WifiLan services.
2024-02-02 10:22:18.028 iOS Example[1804/0x16cebb000] [lvl=2] p2p_cluster_pcp_handler.cc:2212() In StartWifiLanDiscovery(), client=-1399954041333141350 couldn't start scanning on Wifi for service_id=com.rollertoaster.app
2024-02-02 10:22:18.028 iOS Example[1804/0x16cebb000] [lvl=3] p2p_cluster_pcp_handler.cc:998() Failed StartDiscovery() for client=-1399954041333141350 because we couldn't scan on Bluetooth, BLE, or WifiLan for service_id=com.rollertoaster.app
2024-02-02 10:22:18.028 iOS Example[1804/0x16d05f000] [lvl=2] base_pcp_handler.cc:466() Future:[StartDiscovery(com.rollertoaster.app)] completed with status:12
nw_browser_fail_on_dns_error_locked [B1] DNSServiceBrowse failed: NoAuth(18,446,744,073,709,486,061)
```

**Comment by bourdakos1** [comment]
> @live-alchemy
> 
> > Nearby Connections enables advertising, discovery, and connections between nearby devices in a fully-offline peer-to-peer manner.
> 
> I suppose being on the same LAN != being online. So I guess that statement is true since I can have a local network that's not connected to the internet and ios and android would still work. But I agree the wording is confusing. maybe @bourdakos1 can update that text a bit. 😂

That snippet was originally written for Android which supports fully offline transfers. iOS will technically support offline with BLE, but transfers will be very slow. Hotspot could eventually be used for faster offline transfers, but would provide a bit of a disruptive experience since it will show a system prompt when connecting and the user will lose connectivity for the duration of the transfer. We could also add WebRTC for when both devices are connected to separate networks. iOS<>Android fully offline seamless high speed transfers most likely won’t be possible unless Apple adds support for something like Wi-Fi Aware/Direct. I can try to get the snippet updated to be more clear.

**Comment by ColtonIdle** [comment]
Aha. okay. that makes sense. 

So if I have it right. on android it can be fully offline (through wifi direct) but with ios (since it doesn't support wifi direct and instead has its own thing called AWDL) it can't be fully offline.

what about my minor asterik I mentioned above. Can I technically have a local wifi network without internet access, and android to ios should still work right? even though it techncially isn't connected to the "internet"?

**Comment by bourdakos1** [comment]
Yea I think that should work. You should also be able to use Wi-Fi LAN if one of the devices sets up a personal hotspot and both connect to it.
