### ISSUE TITLE
[Nearby Connections] [Android] EndpointDiscoveryCallback -> onEndpointLost callback almost never called

### ISSUE THREAD

**Issue by mannprerak2** [google/nearby#1977]
### Project

Nearby Connections

### Language

Other

### OS Platform

Other

### What happened?

The EndpointDiscoveryCallback -> onEndpointLost callback is almost never called.

I tested this for all strategies, using 2 devices (Pixel 7 and Samsung Galaxy Tab S6 Lite) by advertising by either device, discovering, and then calling stop advertising. I used the [NearbyConnectionsWalkieTalkie sample](https://github.com/android/connectivity-samples/tree/main/NearbyConnectionsWalkieTalkie) for testing. The onEndpointLost callback was very rarely called (Only once in testing it 100s of times).

### What did you expect to happen?

The EndpointDiscoveryCallback -> onEndpointLost callback should be called reliably every time after an endpoint stops advertising after some time.

### How can we reproduce it (as minimally and precisely as possible)?

1. Start discovery on Device 1
2. Start Advertising on Device 2
3. Wait for onEndpointFound to be called on Device 1
4. Stop Advertising on Device 2
5. **Expected**: The onEndpointLost should be called on Device 1 after an interval but is almost never called.

### How often does this bug happen?

Often

### Relevant log output

```shell
D/WalkieTalkie: onEndpointFound(endpointId=3X4F, serviceId=com.google.location.nearby.apps.walkietalkie.automatic.SERVICE_ID, endpointName=03927)
I/alkie.automatic: Compiler allocated 4413KB to compile void android.view.ViewRootImpl.performTraversals()
D/WalkieTalkie: onEndpointFound(endpointId=YLFD, serviceId=com.google.location.nearby.apps.walkietalkie.automatic.SERVICE_ID, endpointName=03927)
D/WalkieTalkie: onEndpointFound(endpointId=JAHV, serviceId=com.google.location.nearby.apps.walkietalkie.automatic.SERVICE_ID, endpointName=29343)
D/WalkieTalkie: onEndpointFound(endpointId=YPXP, serviceId=com.google.location.nearby.apps.walkietalkie.automatic.SERVICE_ID, endpointName=95561)
D/WalkieTalkie: onEndpointFound(endpointId=VB79, serviceId=com.google.location.nearby.apps.walkietalkie.automatic.SERVICE_ID, endpointName=71741)
```

**Comment by bourdakos1** [comment]
@Xlythe can you take a look at this one?

**Comment by Xlythe** [comment]
There was a bug in the #equals method when scanning over BLE which prevented reporting #onEndpointLost. It's been fixed and will roll out to 100% by mid-August.

**Comment by mannprerak2** [comment]
Thanks for the quick response @Xlythe & @bourdakos1 
I'll be on the lookout for the fix!
