### ISSUE TITLE
Cross platform connection failure 

### ISSUE THREAD

**Issue by xuetingwang163** [google/nearby#2021]
We are attempting to establish a connection between an Android phone and an iPhone. However, despite being in the same WIFI LAN, the two devices are unable to discover each other. Upon inspecting the logs, it appears that the iPhone is advertising and discovering on the WIFI_LAN medium, while the Android device is using NFC.

The testing conditions are as follows:
- Both devices are connected to the same WIFI LAN network.
- They are utilizing the same communication strategy (star configuration).
- The same service ID is being used for the communication attempt.

**Comment by bourdakos1** [comment]
Some Wi-Fi networks, like offices or other public networks, don’t allow mDNS. Could you provide more info about your network?

One thing you could try is turning on a hotspot on the android device and connecting the iPhone to it.

**Comment by xuetingwang163** [comment]
Thank you for the prompt response. We are currently operating within an office network. Although I couldn't locate explicit information regarding the allowance of mDNS, the connection was successful after switching to a hotspot.

As for a follow-up question, is it correct to say that WIFI LAN with mDNS is the only method that permits connection and data transfer between Android and iOS devices?

**Comment by bourdakos1** [comment]
Wi-Fi LAN is the only medium we currently support. However, we are working on BLE support which would allow transferring on an office network (or not connected to a network at all), but at much slower speeds.

There are potential mediums we could support that would allow high speed transfers between iOS and Android, with the limitation that both devices need to be connected to some sort of network (doesn’t need to be the same network and would work with office Wi-Fi)

Between Android and Android we support Wi-Fi Direct, which supports high speed transfers with no network connection. 

Between iOS and iOS we could theoretically support high speed transfers with no network connection, but with the current APIs provided by Apple there’s no way to support this between iOS and Android.

hope this helps :)
