### ISSUE TITLE
Possible to expand Build Target to iOS 12?

### ISSUE THREAD

**Issue by xuetingwang163** [google/nearby#2058]
Hi, our app has a build target iOS 12. We are hoping to adopt NearbyConnections. Is it possible to expend and support iOS 12?

**Comment by bourdakos1** [comment]
Unfortunately, much of our code depends on `std::filesystem`, which requires iOS 13: https://developer.apple.com/xcode/cpp/

**Comment by xuetingwang163** [comment]
Thank you for confirming!

**Comment by bourdakos1** [comment]
No problem :)

**Comment by edgarclerigo** [comment]
Hi @xuetingwang163 I'm having the same problem, did you manage any workaround to import NearbyConnections, and keep the iOS12 as the min version?
