### ISSUE TITLE
Wifi Direct for cross platform transferring?

### ISSUE THREAD

**Issue by xuetingwang163** [google/nearby#2075]
Hi there, 

Thanks a lot for your work. 

I learnt from [this documentation](https://developer.android.com/reference/android/net/wifi/p2p/WifiP2pManager#createGroup(android.net.wifi.p2p.WifiP2pManager.Channel,%20android.net.wifi.p2p.WifiP2pManager.ActionListener)) that Android p2pWifiManager allow connection with devices that does not support Wifi Direct. 

Would you consider also utilize Wifi direct for cross platform sharing cases? perhaps use BLE to figure out the medium first?

Thank you!

**Comment by bourdakos1** [comment]
Wi-Fi Direct would be possible for Windows and Linux, but won't be possible for Apple platforms

**Comment by xuetingwang163** [comment]
"[...can accept connections from legacy clients...](https://developer.android.com/reference/android/net/wifi/p2p/WifiP2pManager#createGroup(android.net.wifi.p2p.WifiP2pManager.Channel,%20android.net.wifi.p2p.WifiP2pManager.ActionListener))" 

Can we see iphone as a "legacy client" when there's android phone or other devices that can perform as a designated group owner?

**Comment by bourdakos1** [comment]
I don’t think so

**Comment by Xlythe** [comment]
We use the "legacy client" variant of WiFi Direct in our WiFi Hotspot medium. In legacy mode, the WiFi Direct group owner acts as an access point that other devices can join via SSID/password.

Adding WiFi Hotspot client (not host) support for iOS is one of the open tasks. It causes a pop-up dialog on the iOS device, though, and requires user confirmation, so it's not as seemless as we'd like. Any retries would each, separately, require confirmation too.

It should just require implementing [CreateWifiHotspotMedium](https://github.com/google/nearby/blob/main/internal/platform/implementation/apple/platform.mm#L186), and specifically the [ConnectWifiHotspot](https://github.com/google/nearby/blob/main/internal/platform/wifi_hotspot.h#L183) and [ConnectToService](https://github.com/google/nearby/blob/main/internal/platform/wifi_hotspot.h#L163) methods and returning false for everything else.

**Comment by xuetingwang163** [comment]
Thank you so much for sharing the detailed information.

> We use the "legacy client" variant of WiFi Direct in our WiFi Hotspot medium. In legacy mode, the WiFi Direct group owner acts as an access point that other devices can join via SSID/password.

Do you mean the '"legacy client" + designated group owner' idea is already implemented on Android side? but iphone side is not yet implemented?  

> Adding WiFi Hotspot client (not host) support for iOS is one of the open tasks. It causes a pop-up dialog on the iOS device, though, and requires user confirmation, so it's not as seemless as we'd like. Any retries would each, separately, require confirmation too.

That would be great. is the 'Hotspot' referring to regular wifi hotspot or the wifi direct AP? or both?

**Comment by Xlythe** [comment]
Yes, the legacy client logic (both as a station and an access point) is already implemented for Android and Windows.

The hotspot medium refers to both (and Android has some logic to try legacy WiFi Direct first before same flavors of WiFi hotspot if WiFi Direct is unavailable). Behavior-wise they all act the same, with the one difference being some hotspots also tether data.

**Comment by xuetingwang163** [comment]
That would be great. Could you share an estimated time to support hotspot medium on iOS?

**Comment by Xlythe** [comment]
No timeline at the moment. It's being tracked, but not actively scheduled. Contributions are welcome, though, if you'd like to give it a shot.

**Comment by xuetingwang163** [comment]
Got it. that's all my questions. Thank you @Xlythe @bourdakos1. Appreciate your support!
