### ISSUE TITLE
Unsafe dependency error while building an Xcode flutter project

### ISSUE THREAD

**Issue by tuxpepe1893** [google/nearby#2179]
Hello,

I'm developing a flutter app with native iOS code, I'm trying to use the nearby connections library within my project yet it refuses to compile with the following error:

`Target Integrity (Xcode): The package product 'NearbyCoreAdapter' cannot be used as a dependency of this target because it uses
unsafe build flags`
`Encountered error while building for device.`

Is there a way to enable unsafe compilation within the Xcode part of the project or another way to solve this issue?

Thanks

**Comment by bourdakos1** [comment]
Hmm I’m not sure. Does following this stackoverflow post help? https://stackoverflow.com/questions/67889931/the-package-product-mylibrary-cannot-be-used-as-a-dependency-of-this-target-be

**Comment by tuxpepe1893** [comment]
Sorry for the late response, yes, it helped me a lot , thanks for the response!
