### ISSUE TITLE
Device discovering itself after calling stopAdvertising

### ISSUE THREAD

**Issue by OwenHoffend** [google/nearby#2254]
Hello, I am writing an application that makes use of NearbyConnections' advertising and discovery simultaneously. However, I've encountered some unexpected behavior on Android 14 after running the following (rough) sequence of steps, and I'm trying to understand what is happening:

```
//turn on Nearby
startAdvertising()
startDiscovery()

//turn off Nearby
stopAdvertising()
stopAllEndpoints()
stopDiscovery()

//turn on Nearby a 2nd time
startAdvertising()
startDiscovery()
```

The second call to startDiscovery() results in the device discovering a phantom endpoint from the first call of startAdvertising() for a few seconds before losing it. This also happens after completely closing the app before calling startDiscovery() a second time. If I do this multiple times, I can occasionally get it to discover more than one phantom endpoint from the prior invocations. Any intuition as to why this might be happening? It seems to me that stopAdvertising() isn't entirely releasing the OS resources used for advertising.

Other details that might be relevant:
- I am using P2P_CLUSTER mode
- The bug doesn't seem to happen on Android 12, which I am running on another phone that I have
- Calling startDiscovery() before startAdvertising() seems to fix the problem, but I doubt the above is the intended behavior

**Comment by bourdakos1** [comment]
A potential fix has been submitted and should be live by April 22. Please feel free to re-open if the issue persists :)
