### ISSUE TITLE
Clarification on ultrasonic support

### ISSUE THREAD

**Issue by ColtonIdle** [google/nearby#2280]
Old video... but in https://www.youtube.com/watch?v=Acdu2ZdBaZE they mention using ultrasonic sound. does nearby communication still have this ability now?

**Comment by bourdakos1** [comment]
Nearby no longer supports ultrasonic sound and “Nearby Messages” has been deprecated in favor of Nearby Connections

**Comment by ColtonIdle** [comment]
Cool. Thought so but wanted to make sure. thanks
