### ISSUE TITLE
Issue = invalid custom path 'third_party/protobuf/src' for target 'protobuf'

### ISSUE THREAD

**Issue by hassanAzhar143** [google/nearby#2396]
### Project

Nearby Connections

### Language

Swift

### OS Platform

Apple

### What happened?

the example project is not running at all.
Xcode Version 15.3 
Mac Os 14.2.1 (sonoma)
got error on projects package file
invalid custom path 'third_party/protobuf/src' for target 'protobuf'

### What did you expect to happen?

it should run normally

### How can we reproduce it (as minimally and precisely as possible)?

run it on new xcode
<img width="1391" alt="Screenshot 2024-04-02 at 11 23 50 AM" src="https://github.com/google/nearby/assets/150673894/fdc5f347-1ab4-4c86-9f45-028f491c9657">

### How often does this bug happen?

Every time

**Comment by bourdakos1** [comment]
It’s sounds like the submodules weren’t initialized. Can you try running:

```
git submodule update --init --recursive
```

**Comment by hassanAzhar143** [comment]
OK il try that
