### ISSUE TITLE
Fast Initiation - Windows to Android without Google Files app

### ISSUE THREAD

**Issue by aditya-mankal** [google/nearby#2434]
Hello,

I am creating an app for Windows to share files from Windows to Android. I am able to transfer the files to nearby Android devices, but I need to use Google Files app (or) launch this Activity Intent on the Android device to be able to discover my Android device on Windows.

```
Action: com.google.android.gms.RECEIVE_NEARBY
Mime type: */*
```

I want to avoid the above and achieve Fast Initiation, which I have attempted with these bits. 

```
constexpr uint8_t kFastInitiationServiceId[] = {0xfe, 0x2c};
constexpr uint8_t kFastInitiationModelId[] = {0xfc, 0x12, 0x8e};
```

However, the Android device is not being nudged into a discoverable mode.
Can someone please help me with the right approach to nudge the Android device into a discoverable mode?

![image](https://github.com/google/nearby/assets/162319045/44e1186a-cbde-46bd-bd86-54b130e18dec)

Reference: [fast_initiation_advertiser.cc - chromium](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/chrome/browser/nearby_sharing/fast_initiation/fast_initiation_advertiser.cc)

**Comment by bourdakos1** [comment]
Hey @aditya-mankal, I'm in the process of converting "question" issues into discussions.

The original issue has been converted to a discussion and can be found here:  https://github.com/google/nearby/discussions/2446. I'm going to mark this as a duplicate, but feel free to repost the info as a comment to the discussion. I'll see if I can find more info on the exact advertising format and get back to you in that thread :)

**Comment by aditya-mankal** [comment]
Thank you @bourdakos1! Looking forward to your input on this question. Will keep an eye on this post and also on #2446
