### ISSUE TITLE
Build error in Xcode "clang++: error: no such file or directory: ... PackageFrameworks/NearbyConnectionsDynamic.framework/NearbyConnectionsDynamic"

### ISSUE THREAD

**Issue by Starman3787** [google/nearby#3095]
I'm attempting to make a React Native wrapper for Google Nearby Connections, but am having problems getting it to compile.

This is a link to the repo:

https://github.com/TeamSunride/RNGoogleNearbyConnections

And the error I'm getting currently when trying to build is:

```
Command Ld failed with a nonzero exit code
```

Although when I look at the logs, the actual error is:

```
clang++: error: no such file or directory: '/Users/[name]/Library/Developer/Xcode/DerivedData/RNGoogleNearbyConnections-fodedurdxlzeyaacvrppaevrbxzv/Build/Products/Debug-iphonesimulator/PackageFrameworks/NearbyConnectionsDynamic.framework/NearbyConnectionsDynamic'
```

The package has been added in Xcode by going to `File` => `Add Package Dependencies...` => searching `google/nearby` (as outlined in the docs https://developers.google.com/nearby/connections/swift/get-started)

![Image](https://github.com/user-attachments/assets/6780cbcb-e02c-4960-9796-c2146a9160b9)

and applied to the correct target

the package appears to have been added correctly to "link binary with libraries":

![Image](https://github.com/user-attachments/assets/dce97665-f604-4b3a-8f38-6691fcdd706c)

i've also tried reinstalling the package, but still there is a problem.

`xcodebuild -version` returns:

```
Xcode 16.1
Build version 16B40
```

have i missed something? any guidance on what i should try would be really appreciated.

thanks!

**Comment by bourdakos1** [comment]
@Starman3787 you should only link either `NearbyConnections` or `NearbyConnectionsDynamic`, not both, so that could be causing the linker errors? I would try removing `NearbyConnectionsDynamic` and see if that helps.

**Comment by Starman3787** [comment]
thank you! this fixed the problem. what is the different between `NearbyConnections` and `NearbyConnectionsDynamic`? do they do different things?

**Comment by bourdakos1** [comment]
Awesome! They are the exact same package, one will just be statically linked while the other is dynamically linked. The dynamic version is helpful when used with firebase since we have similar dependencies with some version conflicts, so compiling them statically doesn’t work.
