### ISSUE TITLE
Request for updating the dependency of boringssl-swiftpm, grpc-binary

### ISSUE THREAD

**Issue by cherylEnkidu** [google/nearby#3100]
### Project

Other

### Language

Swift

### OS Platform

Apple

### What happened?

Hi Nearby team,

I am working in Firebase Firestore team and this week we received a ticket regards of the dependency issues caused by the mismatched version of  `boringssl-swiftpm` and `grpc-binary`. https://github.com/firebase/firebase-ios-sdk/issues/14210

Could you please upgrade the dependencies so the developers can enjoy the benefits of both products at the same time? Also the Firestore team would like to work with the Nearby team to make the Google product compatible.  Is there anything we can do to help with dependency changes in the future?

### What did you expect to happen?

N/A

### How can we reproduce it (as minimally and precisely as possible)?

N/A

### How often does this bug happen?

Every time

### Relevant log output

```shell

```

**Comment by bourdakos1** [comment]
@cherylEnkidu thanks for reaching out :) We've previously resolved the issue by exposing a dynamically linked version of NearbyConnections and the use of a module alias for `openssl_grpc`. However, that doesn't seem to be working anymore and I'm not sure if it's from an SPM or Firebase change.

Aside from openssl, the other issue we had was Firebase and Nearby having different C++ requirements, which led us to forking `abseil-cpp-SwiftPM` to support c++17.

I've reopened https://github.com/google/nearby/issues/1916 in favor of this issue as it has more context.
