### ISSUE TITLE
Nearby Connections no option for Earshot distance?

### ISSUE THREAD

**Issue by danielkp1234** [google/nearby#4]
So I am working with trying to transfer data between two phones with Google Nearby Connections.

For example, say I want to transfer a variable from each phone to another and then show a toast containing the text from the other phone.

I have been looking into the Connections API but I can't seem to limit it to when two phones are really close to each other. I have seen that the Nearby Messages API has an Earshot distance option.

But there isn't an option for earshot distance in the Nearby Connections API since the Nearby messages API doesn't seem to contain what I need to make something like the example above work.

Hope you can help me :)

**Comment by apolyudov** [comment]
current version of nearby connections library has no support for earshot, but you could consider BT as an alternative, as it is reasonably short-range as well. There is no plans to add back the old earshot support, as it has multiple limitations. However new kinds of mediums will appear that would let differentiate on distance and possibly direction.

**Comment by danielkp1234** [comment]
@apolyudov  Cool, But is what I am trying possible with Nearby Connections or Nearby Messages. Like holding two devices close together and then check if variable from phone one is higher than the variable from phone 2 then show phone 2 a lost saying it has the lower value and show phone one a toast saying it has the higher value.

**Comment by apolyudov** [comment]
It is possible, if this variable is part of device advertisement. Upper layers of Nearby Connection (such as for example Nearby Messages) may include arbitrary data in their advertisements.

**Comment by danielkp1234** [comment]
@apolyudov Okay, do you have a example i can look at. I also have more phones running the app within 20-100meters. So would need to be able to limit the distance to a very close distance between two phones. So they dont pick up the device that its not intended to. I want it to only connect when a button is pressed on both devices and do what i explained above

**Comment by danielkp1234** [comment]
@apolyudov Will, there be implemented a new Strategy or another way to limit the distance with nearby connections? I find it to be a problem that if I have more devices running the app and they find the wrong device because multiple devices run the app within the 100meters. To solve this they would instead need to find the closest device.

**Comment by apolyudov** [comment]
It is technically possible to estimate distance based on the RSSI value, however this support is not implemented as of today.
IMO, it is a useful feature and we should work on it.

**Comment by wingsofsteel** [comment]
@danielkp1234 what is the rough distance you are trying to set the limit at, and what kind of accuracy are you expecting to achieve?

**Comment by danielkp1234** [comment]
> @danielkp1234 what is the rough distance you are trying to set the limit at, and what kind of accuracy are you expecting to achieve?

I want to limit it to a very close distance. So if 5 devies is running at the same time it will only find the one thats closest  or the device that its being held side by side with.

**Comment by danielkp1234** [comment]
Also is there a check and can do to show a specific message foreach device. Like a text for device 1 that says you win and a text for device 2 that says you lost.

**Comment by apolyudov** [comment]
If these numbers do not change often and small enough to fit in service_id in base64 format, devices may each advertise their numbers (as part of service_id), and discovery will allow them to retrieve each others advertisements and compare numbers.

**Comment by apolyudov** [comment]
Basically, I hear two requests:
1) have some demo code for NC library to demonstrate its basic features
2) add the ability to estimate rough proximity [near, far, etc...] and filter based on that

**Comment by danielkp1234** [comment]
@apolyudov Yes, number 2 is my suggestion.
And yes I don't really understand how I can show a different message to each device in the connection can I do it with an if statement?.

**Comment by danielkp1234** [comment]
And too clarify the data that needs to be exchanged is a firebase user uid from each device then it runs a check and shows a different result on each device.

**Comment by bourdakos1** [comment]
Closing this in favor of the discussion of RSSI in Nearby: https://github.com/google/nearby/discussions/2449
