### ISSUE TITLE
Build failed on Ubuntu 20.04.4 LTS

### ISSUE THREAD

**Issue by senseb** [google/nearby#582]
Follow the build step, build failed, with "Protobuf tests failed; can't use this protobuf."

Env: 
   Description:	Ubuntu 20.04.4 LTS
   Release:	20.04
without local protobuf.

Log here:
[       OK ] IoTest.StringIo (0 ms)
[ RUN      ] IoTest.LargeOutput
CMake Error at cmake/local_build_protobuf.cmake:36 (message):
  Protobuf tests failed; can't use this protobuf
Call Stack (most recent call first):
  CMakeLists.txt:35 (include)

-- Configuring incomplete, errors occurred!
See also "/root/.cache/bazel/_bazel_root/1ce23f7b6c14f468f41df4f296fc9236/execroot/__main__/bazel-out/k8-fastbuild/bin/connections/implementation/ukey2.build_tmpdir/CMakeFiles/CMakeOutput.log".
_____ END BUILD LOGS _____
rules_foreign_cc: Build wrapper script location: bazel-out/k8-fastbuild/bin/connections/implementation/ukey2_foreign_cc/wrapper_build_script.sh
rules_foreign_cc: Build script location: bazel-out/k8-fastbuild/bin/connections/implementation/ukey2_foreign_cc/build_script.sh
rules_foreign_cc: Build log location: bazel-out/k8-fastbuild/bin/connections/implementation/ukey2_foreign_cc/CMake.log

Target //connections:core failed to build
INFO: Elapsed time: 537.925s, Critical Path: 507.26s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully

**Comment by proatgram** [comment]
Did you ever get this issue sorted out? I am having the same issue

**Comment by senseb** [comment]
not yet on linux, finally i use mac to build, maybe you can try building on mac.

**Comment by davidcmoore** [comment]
One of the protobuf tests allocates 4GB of memory. This crashes on resource-constrained systems. I was able to get it to compile by commenting that test out. It's two submodules down, in third_party/ukey2/ukey2/third_party/protobuf:

```
--- a/src/google/protobuf/io/zero_copy_stream_unittest.cc
+++ b/src/google/protobuf/io/zero_copy_stream_unittest.cc
@@ -712,6 +712,7 @@ TEST_F(IoTest, StringIo) {
   }
 }
 
+#if 0
 // Verifies that outputs up to kint32max can be created.
 TEST_F(IoTest, LargeOutput) {
   std::string str;
@@ -726,6 +727,7 @@ TEST_F(IoTest, LargeOutput) {
   output.Next(&unused_data, &size);
   EXPECT_GT(size, 0);
 }
+#endif
 
 
 // To test files, we create a temporary file, write, read, truncate, repeat.
```

**Comment by bourdakos1** [comment]
What commands are you using to build/test?

**Comment by davidcmoore** [comment]
`CC=clang CXX=clang++ bazel build -s --check_visibility=false //connections:core  --spawn_strategy=standalone --verbose_failures`

**Comment by bourdakos1** [comment]
The `ukey2` submodules have been removed and the problematic test was deleted from `protobuf` in https://github.com/protocolbuffers/protobuf/commit/5626baf004c3bb39fd4b362434c3f4cc8cc170f0, so hopefully this is no longer an issue. Feel free to re-open if it persists :)
