### ISSUE TITLE
Use case without bluetooth support? 

### ISSUE THREAD

**Issue by mariusfeldmann** [google/nearby#982]
First of all, thank you for open sourcing this library! 

On my Android phone it says that: Nearby Share uses Bluetooth scanning to find nearby devices. I guess this means that until you get around to implement Bluetooth support, the use cases for this library are pretty limited. Is that correct? 

Or is there a way to force initial discovery to happen via Wifi LAN?

**Comment by bourdakos1** [comment]
Discovery will happen over wifi lan, but Android Nearby Share has additional logic that requires BLE to wake it up and put it in a discoverable mode.

If you know Nearby Share's service ID, Android phones should be able to discover your device using this library. However, for you to be able to discover Android phones, you will need to force the phone into a "discoverable" state. One way to do this is by using the Files by Google app: https://play.google.com/store/apps/details?id=com.google.android.apps.nbu.files&hl=en_US&gl=US

And use the "receive" button:
![image](https://user-images.githubusercontent.com/4212769/197843930-fbbcf32e-4291-48af-aa5c-74f6ead92ea1.png)

Hope this helps :)

**Comment by mariusfeldmann** [comment]
Thank you for the quick reply. Are you able to share the service id of Nearby Share? 👀

**Comment by bourdakos1** [comment]
I don’t remember the service id off the top of my head, but I believe nearby share is open source as part of chromium so you could probably find it by searching their code

**Comment by bourdakos1** [comment]
I think it might just be “NearbySharing” haha https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/nearby_sharing/nearby_sharing_service_factory.cc;l=34

**Comment by mariusfeldmann** [comment]
Ah right, thanks! I updated my code, but there is still nothing really happening when I attempt to establish contact between my Mac and my Pixel. 

Do you see any obvious things that might be wrong with this implementation? 


```
class AppDelegate: NSObject, NSApplicationDelegate, NearbyConnections.AdvertiserDelegate, NearbyConnections.DiscovererDelegate {

    func applicationDidFinishLaunching(_ aNotification: Notification) {

        let title:String = "Foobar"
        let endpointInfo:Data = Data(title.utf8)
        let serviceId:String = "NearbySharing"
        
        let connectionManager = NearbyConnections.ConnectionManager(serviceID: serviceId, strategy: NearbyConnections.Strategy.cluster)
        let advertiser = NearbyConnections.Advertiser(connectionManager:connectionManager)
        advertiser.startAdvertising(using: endpointInfo)
        advertiser.delegate = self
        
        let discoverer = NearbyConnections.Discoverer(connectionManager: connectionManager)
        discoverer.startDiscovery()
        discoverer.delegate = self
    }

    func advertiser(_ advertiser: Advertiser, didReceiveConnectionRequestFrom endpointID: String, with context: Data, connectionRequestHandler: @escaping (Bool) -> Void) {
        print("didReceiveConnectionRequestFrom")
    }

    func discoverer(_ discoverer: Discoverer, didLose endpointID: String) {
        print("didLose")
    }

    func discoverer(_ discoverer: Discoverer, didFind endpointID: String, with context: Data) {
        print("didFind")
    }
}
```

**Comment by bourdakos1** [comment]
I believe Nearby Share uses the `pointToPoint` strategy, so you'll need to update that for them to be able to interact.

You'll also need to add bonjour to your info.plist if you haven't already:
```
<key>NSBonjourServices</key>
<array>
  <string>_FC9F5ED42C8A._tcp</string>
</array>
```

**Comment by mariusfeldmann** [comment]
Thanks for the tips, no luck with that unfortunately. I will do some more digging and report back here if I get anywhere :-)

**Comment by bourdakos1** [comment]
Oh it could be `let endpointInfo:Data = Data(title.utf8)`, the android device would be expecting a specific endpointInfo format, so it will probably ignore you. You should be able to discover android devices though (if you put them into receive mode with the files by google app). Can you share the mac app logs?

**Comment by mariusfeldmann** [comment]
`2022-10-26 20:57:33.278 NearbyShareApp[39455/0x16b2f3000] [lvl=2] ListenForService() [NEARBY] WifiLan Adding server socket, socket_name=-3.51.63.100:30489`

`2022-10-26 20:57:33.281 NearbyShareApp[39455/0x16b37f000] [lvl=1] -[GNCMBonjourBrowser netServiceBrowserWillSearch:] Browsing`

**Comment by bourdakos1** [comment]
Maybe try enabling network entitlements?

**Comment by mariusfeldmann** [comment]
![image](https://user-images.githubusercontent.com/1552570/198123067-f204046f-fed2-435f-bc27-cb1d545bd297.png)


That was one of the first things I checked

**Comment by mariusfeldmann** [comment]
> Oh it could be `let endpointInfo:Data = Data(title.utf8)`, the android device would be expecting a specific endpointInfo format, so it will probably ignore you. You should be able to discover android devices though (if you put them into receive mode with the files by google app). Can you share the mac app logs?


Could you share some more info about the specific endpointinfo format that NearbyShare uses? Or is that proprietary information? Thanks!
